//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anket_Projesi_Ford_Otosan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANK_NESNELER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANK_NESNELER()
        {
            this.ANK_CEVAPLAR = new HashSet<ANK_CEVAPLAR>();
            this.ANK_REFERANSLAR = new HashSet<ANK_REFERANSLAR>();
        }
    
        public int SQ_NESNE_ID { get; set; }
        public string CH_NESNE { get; set; }
        public Nullable<int> CD_EKL_KISI { get; set; }
        public Nullable<System.DateTime> DT_EKL_TARIHI { get; set; }
        public Nullable<int> CD_GUNC_KISI { get; set; }
        public Nullable<System.DateTime> DT_GUNC_TARIHI { get; set; }
    
        public virtual ANK_CALISANLAR ANK_CALISANLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANK_CEVAPLAR> ANK_CEVAPLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANK_REFERANSLAR> ANK_REFERANSLAR { get; set; }
    }
}
