//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anket_Projesi_Ford_Otosan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANK_REFERANSLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANK_REFERANSLAR()
        {
            this.ANK_SORULAR = new HashSet<ANK_SORULAR>();
            this.ANK_CEVAPLAR = new HashSet<ANK_CEVAPLAR>();
        }
    
        public int SQ_REF_ID { get; set; }
        public string CH_REF_ANAHTAR { get; set; }
        public Nullable<int> CD_REF_DEGER { get; set; }
        public string CH_REF_ACIKLAMA { get; set; }
        public Nullable<int> CD_EKL_KISI { get; set; }
        public Nullable<System.DateTime> DT_EKL_TARIHI { get; set; }
        public Nullable<int> CD_GUNC_KISI { get; set; }
        public Nullable<System.DateTime> DT_GUNC_TARIHI { get; set; }
    
        public virtual ANK_CALISANLAR ANK_CALISANLAR { get; set; }
        public virtual ANK_NESNELER ANK_NESNELER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANK_SORULAR> ANK_SORULAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANK_CEVAPLAR> ANK_CEVAPLAR { get; set; }
    }
}
