//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anket_Projesi_Ford_Otosan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANK_CALISANLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANK_CALISANLAR()
        {
            this.ANK_ANKETLER = new HashSet<ANK_ANKETLER>();
            this.ANK_ANKETLER1 = new HashSet<ANK_ANKETLER>();
            this.ANK_CEVAPLAR = new HashSet<ANK_CEVAPLAR>();
            this.ANK_NESNELER = new HashSet<ANK_NESNELER>();
            this.ANK_REFERANSLAR = new HashSet<ANK_REFERANSLAR>();
            this.ANK_SECENEKLER = new HashSet<ANK_SECENEKLER>();
            this.ANK_SECENEKLER1 = new HashSet<ANK_SECENEKLER>();
            this.ANK_SECENEKLER2 = new HashSet<ANK_SECENEKLER>();
            this.ANK_SORULAR = new HashSet<ANK_SORULAR>();
            this.ANK_SORULAR1 = new HashSet<ANK_SORULAR>();
        }
    
        public int SQ_IS_NO { get; set; }
        public string CH_AD { get; set; }
        public string CH_SOYAD { get; set; }
        public string CH_BOLUM { get; set; }
        public string CH_KUL_ADI { get; set; }
        public string CH_SIFRE { get; set; }
        public string CH_MAIL { get; set; }
        public Nullable<bool> SW_YETKI { get; set; }
        public Nullable<int> CD_EKL_KISI { get; set; }
        public Nullable<System.DateTime> DT_EKL_TARIHI { get; set; }
        public Nullable<int> CD_GUNC_KISI { get; set; }
        public Nullable<System.DateTime> DT_GUNC_TARIHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANK_ANKETLER> ANK_ANKETLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANK_ANKETLER> ANK_ANKETLER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANK_CEVAPLAR> ANK_CEVAPLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANK_NESNELER> ANK_NESNELER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANK_REFERANSLAR> ANK_REFERANSLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANK_SECENEKLER> ANK_SECENEKLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANK_SECENEKLER> ANK_SECENEKLER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANK_SECENEKLER> ANK_SECENEKLER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANK_SORULAR> ANK_SORULAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANK_SORULAR> ANK_SORULAR1 { get; set; }
    }
}
