//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anket_Projesi_Ford_Otosan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ANKET_DBEntities : DbContext
    {
        public ANKET_DBEntities()
            : base("name=ANKET_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANK_ANKETLER> ANK_ANKETLER { get; set; }
        public virtual DbSet<ANK_CALISANLAR> ANK_CALISANLAR { get; set; }
        public virtual DbSet<ANK_CEVAPLAR> ANK_CEVAPLAR { get; set; }
        public virtual DbSet<ANK_NESNELER> ANK_NESNELER { get; set; }
        public virtual DbSet<ANK_REFERANSLAR> ANK_REFERANSLAR { get; set; }
        public virtual DbSet<ANK_SECENEKLER> ANK_SECENEKLER { get; set; }
        public virtual DbSet<ANK_SORULAR> ANK_SORULAR { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
