//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnketProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANKT_Secenekler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANKT_Secenekler()
        {
            this.ANKT_Cevaplar = new HashSet<ANKT_Cevaplar>();
        }
    
        public int SecenekID { get; set; }
        public Nullable<int> SoruID { get; set; }
        public string Secenek { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<int> EkleyenKisiID { get; set; }
    
        public virtual ANKT_Calisanlar ANKT_Calisanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANKT_Cevaplar> ANKT_Cevaplar { get; set; }
        public virtual ANKT_Sorular ANKT_Sorular { get; set; }
    }
}
