//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnketProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANKT_Cevaplar
    {
        public int CevapID { get; set; }
        public Nullable<int> SecenekID { get; set; }
        public Nullable<int> SoruID { get; set; }
        public Nullable<int> CevaplayanKisiID { get; set; }
        public string Bilgi { get; set; }
    
        public virtual ANKT_Calisanlar ANKT_Calisanlar { get; set; }
        public virtual ANKT_Secenekler ANKT_Secenekler { get; set; }
        public virtual ANKT_Sorular ANKT_Sorular { get; set; }
    }
}
