//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnketProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANKT_Anketler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANKT_Anketler()
        {
            this.ANKT_Sorular = new HashSet<ANKT_Sorular>();
        }
    
        public int AnketID { get; set; }
        public string Anket { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> YayinTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<int> OlusturanKisiID { get; set; }
    
        public virtual ANKT_Calisanlar ANKT_Calisanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANKT_Sorular> ANKT_Sorular { get; set; }
    }
}
