//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnketProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANKT_Sorular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANKT_Sorular()
        {
            this.ANKT_Cevaplar = new HashSet<ANKT_Cevaplar>();
            this.ANKT_Secenekler = new HashSet<ANKT_Secenekler>();
        }
    
        public int SoruID { get; set; }
        public Nullable<int> AnketID { get; set; }
        public string Soru { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<int> EkleyenKisiID { get; set; }
        public string SoruTipi { get; set; }
    
        public virtual ANKT_Anketler ANKT_Anketler { get; set; }
        public virtual ANKT_Calisanlar ANKT_Calisanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANKT_Cevaplar> ANKT_Cevaplar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANKT_Secenekler> ANKT_Secenekler { get; set; }
    }
}
