//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnketProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANKT_Calisanlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANKT_Calisanlar()
        {
            this.ANKT_Anketler = new HashSet<ANKT_Anketler>();
            this.ANKT_Cevaplar = new HashSet<ANKT_Cevaplar>();
            this.ANKT_Secenekler = new HashSet<ANKT_Secenekler>();
            this.ANKT_Sorular = new HashSet<ANKT_Sorular>();
        }
    
        public int IsNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Bolum { get; set; }
        public string KAdi { get; set; }
        public string Sifre { get; set; }
        public string Mail { get; set; }
        public Nullable<bool> Yetki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANKT_Anketler> ANKT_Anketler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANKT_Cevaplar> ANKT_Cevaplar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANKT_Secenekler> ANKT_Secenekler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANKT_Sorular> ANKT_Sorular { get; set; }
    }
}
